liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        painting_thumb:
            quality: 75
            filters:
               relative_resize:
                    widen: 500
               watermark:
                    image: ../public/imgs/watermark.png
                    size: 0.1
                    position: bottomright

        painting_watermark:
            filters:
               watermark:
                    image: ../public/imgs/watermark.png
                    size: 0.1
                    position: bottomright
