vich_uploader:
    db_driver: orm

    mappings:
        painting_images:
            uri_prefix: '%app.path.painting_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.painting_images%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug'}
